config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: 'users/registrations' }
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get 'up' => 'rails/health#show', as: :rails_health_check

  # Defines the root path route ("/")
  root 'home#index'

  resources :events, only: [] do
    member do
      post :subscribe
    end
  end
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base

  primary_abstract_class

end

app/models/event.rb
# frozen_string_literal: true

class Event < ApplicationRecord

  has_and_belongs_to_many :users # rubocop:disable Rails/HasAndBelongsToMany

  validates :name, presence: true, length: { maximum: 255 }, uniqueness: true
  validates :iterable_event_id, length: { maximum: 36 }

end

app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord

  has_and_belongs_to_many :events # rubocop:disable Rails/HasAndBelongsToMany

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  scope :subscribed_to_event, lambda { |event_name|
    joins(:events).where(events: { name: event_name })
  }

end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base

  rescue_from StandardError do
    render text: 'Internal server error.', status: :internal_server_error
  end

end

app/controllers/events_controller.rb
# frozen_string_literal: true

class EventsController < ApplicationController

  before_action :authenticate_user!

  def subscribe
    event = Event.find(params[:id])
    Events::SubscribeService.new(event:, user: current_user).call
    flash[:notice] = "Successfully subscribed to #{event.name}"

    redirect_to root_path
  end

end

app/controllers/home_controller.rb
# frozen_string_literal: true

class HomeController < ApplicationController

  def index
    @events = Event.all
  end

end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

module Users
  class RegistrationsController < Devise::RegistrationsController

    def create
      super

      CreateUserInIterableService.new(user: resource).call
    end

  end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper

  def flash_message_prefix(message_type)
    case message_type
    when 'success' then t('alert_prefix.success')
    when 'info'    then t('alert_prefix.info')
    when 'warning' then t('alert_prefix.warning')
    when 'danger'  then t('alert_prefix.danger')
    else ''
    end
  end

  def message_type(message_type)
    case message_type
    when 'notice' then t('message_type.notice')
    when 'alert'  then t('message_type.alert')
    else message_type
    end
  end

end

app/views/home/index.html.erb
<h1>Events</h1>

<div class="card" style="width: 30rem;">
  <div class="card-body">
    <% @events.each do |event| %>
      <%= button_to "Subscribe To #{event.name}", subscribe_event_path(event.id), method: :post, class: "btn btn-primary mt-2"  %>
      <br>
    <% end %>
  </div>
</div>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container-fluid">
    <a class="navbar-brand" href="<%= root_path %>">Event Manager</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav ms-auto mb-2 mb-lg-0">

        <% if user_signed_in? %>
          <li class="nav-item">
            <span class="nav-link">
              <%= current_user.email %>
            </span>
          </li>
        <% end %>

        <li class="nav-item">
          <% if user_signed_in? %>
            <%= button_to 'Logout', destroy_user_session_path, method: :delete, class: 'nav-link', data:{ turbo: "false" } %>
          <% else %>
            <%= link_to 'Login', new_user_session_path, class: 'nav-link' %>
          <% end %>
        </li>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>IterableDotComIntegration</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= render 'layouts/navbar' %>

    <div class="container">
      <% flash.each do |message_type, message| %>
        <div class="alert alert-<%= message_type(message_type) %> mt-2">
          <p class="mb-0">
            <%= flash_message_prefix(message_type(message_type)) %>
            <%= message %>
          </p>
        </div>
      <% end %>

      <div class="mt-4">
        <%= yield %>
      </div>
    </div>
  </body>

  <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.10.2/dist/umd/popper.min.js" integrity="sha384-7+zCNj/IqJ95wo16oMtfsKbZ9ccEh31eOz1HGyDuCQ6wgnyJNSYdrPa03rtR1zdB" crossorigin="anonymous"></script>
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.min.js" integrity="sha384-QJHtvGhmr9XOIpI6YVutG+2QOK9T+ZnN4kzFN1RtK3zEFEIsxhlmWl5/YESvpZ13" crossorigin="anonymous"></script>
</html>